- name: Baixar o arquivo do Terraform
  get_url:
    url: "https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip"
    dest: "/tmp/terraform.zip"

- name: Instalar o unzip
  apt:
    name: unzip
    state: present

- name: Extrair o arquivo do Terraform
  unarchive:
    src: "/tmp/terraform.zip"
    dest: "/usr/local/bin"
    remote_src: yes

- name: Definir permissões do Terraform
  file:
    path: "/usr/local/bin/terraform"
    mode: "u+x,g+x"

- name: Remover o arquivo do terraform
  file:
    path: "/tmp/terraform.zip"
    state: absent