- name: config_local
  hosts: localhost
  user: "{{ username }}"
  become: true
  become_method: sudo
  connection: local

  roles:
    - role: config_local

#ansible-playbook -k -i localhost --extra-vars="username= git_user_name='' git_user_email= git_user_force=" deployment.yml