- name: config_local
  hosts: localhost
  user: "{{ username }}"
  become: true
  become_method: sudo
  connection: local

  roles:
    - role: config_local

#sudo ansible-playbook -k -i localhost --extra-vars="username=" deployment.yml
